"""films table

Revision ID: 2873446b3f33
Revises: 3eacd320906b
Create Date: 2020-11-18 21:01:32.824822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2873446b3f33'
down_revision = '3eacd320906b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('city', sa.String(length=1024), nullable=True))
    op.add_column('movies', sa.Column('genre', sa.String(length=1024), nullable=True))
    op.add_column('movies', sa.Column('year', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'year')
    op.drop_column('movies', 'genre')
    op.drop_column('movies', 'city')
    # ### end Alembic commands ###
