"""films table

Revision ID: 9a8e39008a69
Revises: e8e07edae414
Create Date: 2020-11-18 22:52:41.390938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8e39008a69'
down_revision = 'e8e07edae414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'genre')
    op.drop_column('movies', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('city', sa.VARCHAR(length=1024), nullable=True))
    op.add_column('movies', sa.Column('genre', sa.VARCHAR(length=1024), nullable=True))
    # ### end Alembic commands ###
