"""films table

Revision ID: e8e07edae414
Revises: 2873446b3f33
Create Date: 2020-11-18 22:46:31.031748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e07edae414'
down_revision = '2873446b3f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'genre')
    op.drop_column('movies', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('city', sa.VARCHAR(length=1024), nullable=True))
    op.add_column('movies', sa.Column('genre', sa.VARCHAR(length=1024), nullable=True))
    # ### end Alembic commands ###
