"""films table

Revision ID: f6850d1b4127
Revises: 9a8e39008a69
Create Date: 2020-11-18 22:56:01.846520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6850d1b4127'
down_revision = '9a8e39008a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'genre')
    op.drop_column('movies', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('city', sa.VARCHAR(length=1024), nullable=True))
    op.add_column('movies', sa.Column('genre', sa.VARCHAR(length=1024), nullable=True))
    # ### end Alembic commands ###
